{
  "uid" : "7fd70bc821ea23bf",
  "name" : "Test Authorization authorized user AWDEV-T491",
  "fullName" : "tests.ui.test_authorization_user.TestRegistrationUser#test_authorization_user_awdew_t491",
  "historyId" : "ad0fa193154ae62618381a87ad8c3e13",
  "time" : {
    "start" : 1723560988777,
    "stop" : 1723560988777,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/127.0.6533.99/chromedriver unexpectedly exited. Status code was: 127",
  "statusTrace" : "pytestconfig = <_pytest.config.Config object at 0x7f76d27675b0>\nrequest = <SubRequest 'set_driver' for <Function test_authorization_user_awdew_t491[{'name': '\\u0414\\u0438\\u043c\\u0430', 'phone': '+380637203664'}-8889]>>\n\n    @pytest.fixture(autouse=True)\n    def set_driver(pytestconfig, request):\n        driver = None\n        browser = pytestconfig.getoption(\"--browser_name\")\n        if browser == \"chrome\":\n            chromedriver_autoinstaller.install()\n            options = webdriver.ChromeOptions()\n            options.add_argument(\"--headless\")\n            options.add_argument(\"--no-sandbox\")\n            options.add_argument(\"--disable-dev-shm-usage\")\n            options.add_argument(\"--window-size=1920,1080\")\n>           driver = webdriver.Chrome(options=options)\n\ntests/ui/conftest.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n../local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py:55: in __init__\n    self.service.start()\n../local/lib/python3.10/site-packages/selenium/webdriver/common/service.py:102: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.chrome.service.Service object at 0x7f76cc160a90>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/127.0.6533.99/chromedriver unexpectedly exited. Status code was: 127\n\n../local/lib/python3.10/site-packages/selenium/webdriver/common/service.py:115: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "set_env_settings",
    "time" : {
      "start" : 1723560979350,
      "stop" : 1723560979351,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "set_driver",
    "time" : {
      "start" : 1723560988778,
      "stop" : 1723560989607,
      "duration" : 829
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/127.0.6533.99/chromedriver unexpectedly exited. Status code was: 127\n\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/usr/workspace/tests/ui/conftest.py\", line 23, in set_driver\n    driver = webdriver.Chrome(options=options)\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 55, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py\", line 102, in start\n    self.assert_process_still_running()\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py\", line 115, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true
  }, {
    "name" : "pytestconfig",
    "time" : {
      "start" : 1723560979350,
      "stop" : 1723560979350,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1723560979267,
      "stop" : 1723560979350,
      "duration" : 83
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "tests.ui"
  }, {
    "name" : "suite",
    "value" : "test_authorization_user"
  }, {
    "name" : "subSuite",
    "value" : "TestRegistrationUser"
  }, {
    "name" : "host",
    "value" : "58705c7a1f91"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.ui.test_authorization_user"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "code",
    "value" : "8889"
  }, {
    "name" : "user",
    "value" : "{'name': 'Дима', 'phone': '+380637203664'}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 5,
        "skipped" : 0,
        "passed" : 3,
        "unknown" : 0,
        "total" : 8
      },
      "items" : [ {
        "uid" : "71bd29b819ca3b82",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/127.0.6533.99/chromedriver unexpectedly exited. Status code was: 127",
        "time" : {
          "start" : 1723548584109,
          "stop" : 1723548584109,
          "duration" : 0
        }
      }, {
        "uid" : "dfcd4d546e06f4f5",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/127.0.6533.99/chromedriver unexpectedly exited. Status code was: 127",
        "time" : {
          "start" : 1723533074506,
          "stop" : 1723533074506,
          "duration" : 0
        }
      }, {
        "uid" : "4308f784684c4c0c",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x7f09a1a27e3a <unknown>\n#1 0x7f09a171145c <unknown>\n#2 0x7f09a175d5b5 <unknown>\n#3 0x7f09a175d671 <unknown>\n#4 0x7f09a17a1f14 <unknown>\n#5 0x7f09a17804dd <unknown>\n#6 0x7f09a179f2cc <unknown>\n#7 0x7f09a1780253 <unknown>\n#8 0x7f09a17501c7 <unknown>\n#9 0x7f09a1750b3e <unknown>\n#10 0x7f09a19ee27b <unknown>\n#11 0x7f09a19f2327 <unknown>\n#12 0x7f09a19dadae <unknown>\n#13 0x7f09a19f2df2 <unknown>\n#14 0x7f09a19bf74f <unknown>\n#15 0x7f09a1a17128 <unknown>\n#16 0x7f09a1a172fb <unknown>\n#17 0x7f09a1a26f6c <unknown>\n#18 0x7f09a2295349 <unknown>",
        "time" : {
          "start" : 1718559025773,
          "stop" : 1718559052587,
          "duration" : 26814
        }
      }, {
        "uid" : "5f1e00eee2d89e40",
        "status" : "passed",
        "time" : {
          "start" : 1718551852143,
          "stop" : 1718551860754,
          "duration" : 8611
        }
      }, {
        "uid" : "db4dee6963b04957",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x7f69f5a38e3a <unknown>\n#1 0x7f69f572245c <unknown>\n#2 0x7f69f576e5b5 <unknown>\n#3 0x7f69f576e671 <unknown>\n#4 0x7f69f57b2f14 <unknown>\n#5 0x7f69f57914dd <unknown>\n#6 0x7f69f57b02cc <unknown>\n#7 0x7f69f5791253 <unknown>\n#8 0x7f69f57611c7 <unknown>\n#9 0x7f69f5761b3e <unknown>\n#10 0x7f69f59ff27b <unknown>\n#11 0x7f69f5a03327 <unknown>\n#12 0x7f69f59ebdae <unknown>\n#13 0x7f69f5a03df2 <unknown>\n#14 0x7f69f59d074f <unknown>\n#15 0x7f69f5a28128 <unknown>\n#16 0x7f69f5a282fb <unknown>\n#17 0x7f69f5a37f6c <unknown>\n#18 0x7f69f62a6349 <unknown>",
        "time" : {
          "start" : 1718551126928,
          "stop" : 1718551153039,
          "duration" : 26111
        }
      }, {
        "uid" : "84db97be996b1647",
        "status" : "passed",
        "time" : {
          "start" : 1718549916502,
          "stop" : 1718549926240,
          "duration" : 9738
        }
      }, {
        "uid" : "3ac1f03b93b7bc80",
        "status" : "passed",
        "time" : {
          "start" : 1718549490818,
          "stop" : 1718549500809,
          "duration" : 9991
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "7fd70bc821ea23bf.json",
  "parameterValues" : [ "8889", "{'name': 'Дима', 'phone': '+380637203664'}" ]
}